### ISSUE TITLE
How to get frames most stably? 

### ISSUE THREAD

**Issue by anl13** [Aqueti/mantis_examples#10]
I would like to get frames from all camera at the same time stably. 
When I use `MantisGetFrames.c` example to get frames, which use 
```
getFrame(myMantis, 
                               mcamList[i].mcamID,
                               0,
                               ATL_TILING_1_1_2,
                               ATL_TILE_4K);
```
It may fails randomly at some mcamID. 
When I use 
```
getFrame(myMantis, 
                               mcamList[i].mcamID,
                               timestamp,
                               ATL_TILING_1_1_2,
                               ATL_TILE_4K);
```
instead, where `timestamp` is the timestamp of frame got at first mcam, it may get all frames normally, or still fails randomly at some mcamID, but more stable. 
Now my solution is that iteratively use `getFrame` to query the same mcam if it fails, until succeed to save a frame at target timestamp. But such a solution is too tricky. 
So, **question** is:
How to get frames most stably? Can the fails be solved?

**Comment by russell-taylor** [comment]
The algorithm that you are using, selecting one time for all cameras and then adjusting the timestamp for any camera that has a missing frame at that time, matches the one we use internally for capturing frames to use for stitching.  We're continuing to improve the fraction of frames that are captured with the goal that no frame is lost from any camera, at which point the algorithm will work without having to try different timestamps.

Your idea of using the first timestamp at some camera, rather than 0, is a good one.

If you require consistent timestamps across all cameras, you should be able to request new images from all cameras at the updated timestamp, rather than just from the camera that was missing.  There should be times where all cameras have images.

**Comment by russell-taylor** [comment]
@uberferg @sfeller Do we want to consider adding a time interval query to the API, so that someone could request a frame not just at a specific time but anywhere within a range of times, so that this searching work is done inside the API rather than by the user application?

**Comment by sfeller** [comment]
I think we should be able to get the frame in the "bin" for the closest time. We should know the fps of the camera, so we can map the time to the closest frame and still know if the frame is missing.

**Comment by uberferg** [comment]
@sfeller all time binning done for the render requests are internal to the DataManager, and therefore we're also doing the same binning for individual requests done through the API. The code for both requests is almost identical, with the only difference being that API requests are already in timestamps, and do not need to first be converted from frame numbers.

I am able to use SaveClip.c, getClipList.c, and getClipMCamImages to retrieve a very high percentage of frames for a recorded clip (with the caveat that the clip needs to be stored on several drives, or saving to disk may be too slow and containers will be dropped). There is a bug that causes the PropertyManager to give bad mcam IDs the first time it syncs to V2, and therefore requests fail because the requested ID's do not exist, but every subsequent time the requests succeed for over 99% of frame requests. I've made a separate issue for the PropertyManager bug as Aqueti/atl#102.

Requesting the most recent frame (timestamp 0) seems to still have a bug that I need to work out that causes it to fail about ~25% of the time. This is independent of the fact that this type of request also has to deal with the ProeprtyManager bug mentioned above, and refers to the failure rate of requests after the first sync attempt.

**Comment by uberferg** [comment]
Fixed most recent frame issue. It was the same issue that was causing us to miss frames in the cache when rendering a few weeks ago. Implemented essentially the same fix by subtracting 1 frame to correct for the possibility that the actual most recent frame has only arrived for 1 of the 2 scales and the user requested the one that is still in on its way.

**Comment by uberferg** [comment]
@sfeller Can we mark this as closed? I think we solved the issue where we were failing to return most recent frames ~25% of the time. As for returning specific timestamp requests within a certain range, that works as well as it can, and only returns failures when we drop frames.

The only remaining issues with this functionality are some wider issues with connecting API instances to Tegras/V2, which occasionally fails for reasons I think we're still trying to debug. These issues only pop up on occasion and aren't directly related to the original concern of this post.

**Comment by sfeller** [comment]
I believe this issues has been addressed. The question as to how to best get frames has been answered and the fixes mentioned have contributed to overall stability. I am closing this issue. Any future stability problems should be new tickets.
