### ISSUE TITLE
Evetar_AutoFocus.cpp can not set the correct focus

### ISSUE THREAD

**Issue by yuanxy92** [Aqueti/mantis_examples#17]
Output:
[log.txt](https://github.com/Aqueti/mantis_examples/files/1046744/log.txt)

The autofocusing result is not right for most cameras.
![screenshot](https://cloud.githubusercontent.com/assets/4077402/26712232/6470c510-4798-11e7-816f-64e27c99984d.jpg)
I find that the preview camera images in Nous are very bright during autofocusing. I think it may cause the metric to fail.

**Comment by smccain** [comment]
Did you update the moveFocusMotor.py script in install/bin on the Tegras?

**Comment by smccain** [comment]
also these are Evetar sensor modules not leopard?

**Comment by smccain** [comment]
Also if you could save the terminal output to a txt file we could see better what went wrong

**Comment by yuanxy92** [comment]
Thanks, we will use new python script to test tomorrow.

**Comment by newdee** [comment]
en, we've used the new python script to 'AutoFocus', but it seems to be not helpful. It cannot set the correct focus and I have upload the logs file and screenshot of two cameras' image.(1.0 and 2.0 are original images, 1.1 and 2.1 are images after running this AutoFocus)

[log.txt](https://github.com/Aqueti/mantis_examples/files/1049518/log.txt)


![1 0](https://cloud.githubusercontent.com/assets/12610440/26752602/33e48488-4886-11e7-804a-5a7c9124ee6f.png)



![2 0](https://cloud.githubusercontent.com/assets/12610440/26752620/9f29bf9c-4886-11e7-87e1-1a4d3f618b02.png)
![1 1](https://cloud.githubusercontent.com/assets/12610440/26752621/aeb75fbe-4886-11e7-9d72-416b2301b21f.png)
![2 1](https://cloud.githubusercontent.com/assets/12610440/26752622/b4f95f6c-4886-11e7-97b7-58d986a3cc6d.png)

**Comment by smccain** [comment]
In CamViewer when you move the focus motor 0 steps, it should move itself all the way to position 0, please verify this is the case. If not Hongyuan or someone needs to go to camera operations and get the lastest moveFocusMotor.py and load it onto the Tegras

Also, does Mantis Camera Focus work? Do you see the overlay and metric calculate correctly?

**Comment by newdee** [comment]
We have tested this case, and move the focus motor 0 steps. It  focus correctly first, and after using the AutoFocus script. it became blurry.
We've not tested the Mantis_Camera_Work, but we'll test it soon.

**Comment by yuanxy92** [comment]
I tested Mantis_Camera_Focus, there are some problems: (auto focus still not work)
1) I can use i and o to adjust the focus. However, it seems that the right focus is not in the adjustable range. I want to use o to make the better focus better, but o does not work anymore.
2) Shown in image: (it detects some edges, but not on the real objects)
![2](https://cloud.githubusercontent.com/assets/4077402/26753226/76effd8a-4894-11e7-9362-a0bc1eaac2c4.jpg)

**Comment by yuanxy92** [comment]
We tested the autofocus again, and we find the problem is that the step size is too large. (default is 100).
Red arrows denote the sampling point, black curve denote the metric value. Using stepsize 100 to scan the focus range can not find the right position.
![sample](https://cloud.githubusercontent.com/assets/4077402/26768695/43b2c5ee-49dc-11e7-91f0-3090460f471b.jpg)

**Comment by yuanxy92** [comment]
We find one more problem this afternoon.
Before running Evetar_AutoFocus, we can use CamViewer to adjust the camera focus well. However, after running Evetar_AutoFocus, we can not do it any more. (clicking near doesn't change the image)
We have to power off and power on to make it work again.

I think it is because Evetar_AutoFocus changes the setting of camera.

**Comment by yuanxy92** [comment]
I did another test, I modify the code:
1. set adjustable range to (0, 500)
2. set the step to 50
and it works.
I think it maybe a hardware problem. If I run the original code, the cameras can not be focused any more unless I power off and power on them.

Besides, why use canny edge as metric?

**Comment by bmaione** [comment]
We use canny because it is easy to implement with openCV functions and it seems to give the best metric contrast between in focus images and out of focus images. I can imagine a scenario where the focus distance is very narrow, resulting in a near delta function in the autofocus metric, thus if the step size is too large, the best focus search will miss the best focus position all together. I will add a command line argument to pass the step size in to the executable. Another option is to use a different edge detection method, I'll try that also.

**Comment by bmaione** [comment]
In terms of camViewer use, please close camviewer before running the autofocus script, and the reopen it after the autofocus script has finished. 

Also the focus controls may be inverted i.e. near = far and far = near. Please try this and verify that it does/doesn't work.

**Comment by yuanxy92** [comment]
@bmaione
We close camviewer before running the autofocus script, and the reopen it after the autofocus script has finished. We already try both near and far in CamViewer.

Now the problem is that too large scan range (eg. 0-2200) will cause the camera can not be focused again using CamViewer.

**Comment by bmaione** [comment]
That scan range is fine. The maximum position of the motor is 2294. But I also have encountered this issue, at the end of coarse focus sweep, it's necessary to send a command twice to clear an error state on the motor. I'm not sure why it's going in to an error state. I'll look in to this more today.

**Comment by whyuan1221** [comment]
Autofocus script will put the motor in a still state (We can't change the focus state even in Camviewer after running move focus code). And I don't know if it a good idea to set the stepwise to a smaller value  because the more we move the motor, the hotter the motor will be. I tried to move the motor few times, the motor got hot afterwards.

**Comment by sfeller** [comment]
@bmaione, any updates?

**Comment by bmaione** [comment]
The focusing aspect should be fixed. When Bradly and I were looking at it, it worked well and repeatably every other time, every other operation the application receives null frames from the McamAPI. I believe Bradly was looking into this. @bjschwa2

**Comment by yuanxy92** [comment]
@sfeller @bmaione @smccain 
I found two problems these days:
1. I saved all the images during scanning the range (e.g. 0-2200, with step 100), and the algorithm can successfully one value is the best (e.g. 1000).  After that, the code set the focus to 1000, however, I find that the image is much more blurry than the saved 1000. It seems that the focus position is not reliable.
2. For some cameras, when adjusting the camera focus in CamViewer, you can find that: If you are in  best focus position, and you click "far" once, it become worse. However, if you want to move the camera focus to the best position again, you need to click "near" more than once, which is very weird.

**Comment by bmaione** [comment]
@yuanxy92 
I'm not entirely clear on what you mean by (1).

But (2) is not surprising. When you change the motor direction you have to overcome the motor hysteresis. For example is you step near 500 steps and then try and step far 500 steps you do not return to the same position in which you started.

In the autofocus code this is why we do a coarse search and then a fine sweep. Basically the algorithm steps through focus in 100 step increments and records the best position. leaving a 200 step ambiguity to where actual best focus may be.

After which the code then returns to ~100 steps before the best focus position and steps small increments (10) until the metric decrease, at which point you're sure that you've gone through the global best focus position.

**Comment by yuanxy92** [comment]
@bmaione @whyuan1221 
Thanks. I have one more questions about (2):
I want to know if I let the motor back to the zero position, is it has the same problem with (2) ?
if yes, it means that when I let the motor back to the zero position, it does not go back the nearest position physically. Is there any method to know if it reaches nearest physically?

For problem (1), I skipped the fine sweep step (comment the code) because I found that the result is not good and I want to figure out why? And I encountered the problem (1). It seems that problem (1) and problem (2) caused by the same reason.

**Comment by bmaione** [comment]
I modified movefocusmotors.py on the tegra such that, when you pass 0 into the focus command (i.e. setMCamFocusNear(mcam, 0)) it will return to the physical motor stop (position zero). An example of this is on line 246 in Evetar_Auto_Focus.cpp. If you enter 0 for the number of steps in camviewer and hit the focus but it should have the same effect. 

From the limited testing that I've done Evetar_Auto_Focus works well ~85% of the time, which is approximately what I was expecting. The intention was to get the focus close using the autofocus script and then make fine adjustments with Mantis_Camera_Focus.

For (1), the motors are unidirectional, for example if the focus search finds the best position to be (1000), in order to return to position 1000 after ending at the furthest focus position, the motor must first go to position (0), and then to position (1000).

This can be accomplished by:
setMCamFocusNear(mcamList[i], 0); ----> goes to position zero
sleep(3); Wait for the motor to return to position zero
setMCamFocusFar(mcamList[i], 100-); ----> goes to position 1000


Is that helpful?

**Comment by bmaione** [comment]
I wrote a new focus class that should enable us to autofocus a single microcamera in camviewer. Closing this issue for now.
