### ISSUE TITLE
Image metadata not making it to  V2 or saved to metadata files

### ISSUE THREAD

**Issue by sfeller** [Aqueti/mantis_examples#4]
Need to make sure image metadata makes to the render system and stored files.

**Comment by camerongivler** [comment]
@bjschwa2 is this resolved?

**Comment by bjschwarz** [comment]
I have validated that correct metadata is saved in the saveMCamFrame. I
believe this could segfault if you don't have write permission to the
directory, I will work on debugging this today. The V2 part is a separate
issue. I have not been aware of this issue.

**Comment by uberferg** [comment]
metadata is definitely reaching V2 because it is used to generate the keys to store images in the datamanager. If we were not receiving the metadata, then we would see a lot of errors that keys already exists, because multiple keys would be generated from the default uninitialized metadata values.

If you mean that you are expecting to see JSON files for the metadata of images in the folders with the HContainers, that's just not a thing that the storage manager does because we would have a huge number of files in each directory. The metadata is in the images inside the HContainers and can be accessed through the API.

**Comment by sfeller** [comment]
OK, it sounds like we can close this. Let me know if I need to reopen
